title: Edgard Collante - Hoja De Vida
locale: es_CO
lang: es_CO
tagline: Mi experiencia de trabajo, educación y certificados
description: Mi experiencia de trabajo, educación y certificados
logo: /assets/img/logo.png
author: Edgard Collante
plugins:
  - jekyll-seo-tag
