name: 'Lint English'
description: 'Lints md files for english writing.'
runs:
  using: "composite"
  steps: 
    - run: python -m pip install proselint
      shell: python
    - run: proselint ${{ github.workspace }}/**.md 
      shell: python
