on: [push]

jobs:
  proselint-job:
    runs-on: ubuntu-latest
    name: Lints md files for good english
    steps:
    - uses: actions/checkout@v2
    - id: lint-english
      uses: ./.github/actions/proselint #@v1
