on: [push]

jobs:
  proselint-job:
    runs-on: ubuntu-latest
    name: Lints md files for good english
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Proselint
      run: python -m pip install proselint
    - name: Lint English 
      run: proselint {{ github.workspace }}/**.md
