name: Lint English

on: [push]

jobs:
  proselint-job:
    runs-on: ubuntu-latest
    name: Lints md files for good english
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Proselint
      run: python -m pip install proselint
    - name: Lint English 
      run: proselint ${{ github.workspace }}/**.md
